### ISSUE TITLE
Error While running

### ISSUE THREAD

**Issue by othreecodes** [erdem/django-admino#10]
Hello, I installed this project via pip, but it seems to not be working, peharps a mssing dependency or something. here's the stacktrace
```bash
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f87a3c381e0>
Traceback (most recent call last):
  File "/root/PycharmProjects/badgeaas/venv/lib/python3.5/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/root/PycharmProjects/badgeaas/venv/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 113, in inner_run
    autoreload.raise_last_exception()
  File "/root/PycharmProjects/badgeaas/venv/lib/python3.5/site-packages/django/utils/autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "/root/PycharmProjects/badgeaas/venv/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/root/PycharmProjects/badgeaas/venv/lib/python3.5/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/root/PycharmProjects/badgeaas/venv/lib/python3.5/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/root/PycharmProjects/badgeaas/venv/lib/python3.5/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/root/PycharmProjects/badgeaas/venv/lib/python3.5/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/root/PycharmProjects/badgeaas/venv/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 985, in _gcd_import
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 957, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 697, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/root/PycharmProjects/badgeaas/venv/lib/python3.5/site-packages/admino/__init__.py", line 1, in <module>
    from sites import site
ImportError: No module named 'sites'

```

**Comment by othreecodes** [comment]
@erdem Is there something im missing?

**Comment by shahraizali** [comment]
having the same issue!! @othreecodes did something work out for you ??

**Comment by magic5650** [comment]
> having the same issue!! @othreecodes did something work out for you ??

from admino.sites import site

**Comment by erdem** [comment]
@shahraizali I didn't develop this project for a long time. Probably, it is not compatible with Django 2.x versions.
